### PR TITLE
add machine-namespace

### PR DESCRIPTION
**Pull request by hanqiuzh**
Updates:
- Added `--machine-namespace` as a new argument to list machine in a namespace. 
   If not given, will list machines in cluster scope. (same as before)

### CODE REVIEW

**Comment by hanqiuzh** [comment]
/assign @alexander-demichev @JoelSpeed @enxebre 

Hi, please review when you have time, and please let me know your thoughts 👍

**Review by JoelSpeed — COMMENTED** [review]
Apart from the flag name, LGTM, please see the comment inline

**Comment by hanqiuzh** [comment]
@JoelSpeed thanks a lot. All updated. Please check again.

**Review by alexander-demichev — APPROVED** [review]
thanks
/approve

**Pull request merged**
