### PR TITLE
Add techpreview manifests for CAPI machines

### PR DESCRIPTION
**Pull request by alexander-demichev**
Add techpreview manifests for CAPI machines, this is the easiest way to have CMA work with CAPI machines in techpreview phase.

### CODE REVIEW

**Review by damdo — COMMENTED** [review]
/lgtm

**Comment by lobziik** [comment]
Would be awesome to enable TP ci first...

**Review by elmiko — COMMENTED** [review]
/approve

**Comment by elmiko** [comment]
/approve cancel

sorry, i didn't see @lobziik 's comment

**Pull request merged**
