### PR TITLE
Bug 1909108: Bump K8s dependencies to 1.20

### PR DESCRIPTION
**Pull request by JoelSpeed**
What it says on the tin. Bumps K8s dependencies to v1.20 to be inline with OCP 4.7

### CODE REVIEW

**Review by elmiko — APPROVED** [review]
/lgtm

**Comment by JoelSpeed** [comment]
/hold

This is currently broken, investigating

```
/usr/bin/machine-approver flag redefined: kubeconfig
panic: /usr/bin/machine-approver flag redefined: kubeconfig

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc0001b2120, 0x1d62fe0, 0xc000146080, 0x1b451fc, 0xa, 0x1b66ac8, 0x24)
	/usr/lib/golang/src/flag/flag.go:851 +0x485
flag.StringVar(...)
	/usr/lib/golang/src/flag/flag.go:760
main.main()
	/go/src/github.com/openshift/cluster-machine-approver/main.go:268 +0x118
```

**Comment by JoelSpeed** [comment]
/hold cancel

Cluster Machine Approver was importing MAPI v1beta1 which in turn imported controller-runtime/pkg/client/config which was registering a kubeconfig flag, causing the double registration. Have fixed this by using our own flagset for CMA

**Review by elmiko — APPROVED** [review]
/lgtm

**Pull request merged**
