### PR TITLE
Bug 1978303: update approve condition logic

### PR DESCRIPTION
**Pull request by elmiko**
This change updates the approval condition logic to detect when the
condition already exists in the CSR record. If the condition already
exists, and has a different state than is desired, the condition will be
updated. If the condition does not exist, it will be created and added
to the CSR record.

When the condition does not need to be updated, the approve logic will
now skip sending an update to the API server.

### CODE REVIEW

**Comment by elmiko** [comment]
@JoelSpeed ptal, the function in the mao is slightly different (more generic), so i've modified it for this application. i did look at library-go to see about possibly creating a common function for this, but i think we will need to do some planning if we want to realize that as we need to analyze the various usages and build a function that can work in multiple places and for multiple condition types.

**Review by JoelSpeed — COMMENTED** [review]
/approve

**Review by damdo — COMMENTED** [review]
/lgtm

**Pull request merged**
