### PR TITLE
OCPCLOUD-1805: Port to ginkgo v2

### PR DESCRIPTION
**Pull request by Fedosin**
This commit ports tests to ginkgo v2 framework.

### CODE REVIEW

**Comment by elmiko** [comment]
the change looks good to me, not sure why the unit test is failing
/retest

**Comment by JoelSpeed** [comment]
Do we want to include junit and coverage changes here?

**Comment by odvarkadaniel** [comment]
> Do we want to include junit and coverage changes here?

These are covered in #178.
Otherwise the changes look good to me.
/lgtm

**Pull request merged**
