### PR TITLE
OCPBUGS-1411: Bump k8s dependencies to 1.25

### PR DESCRIPTION
**Pull request by lobziik**
Also upd controller-runtime and openshift/api

Also fake clock for testing now imports from "k8s.io/utils", since this types was removed from apimachinery, see: https://github.com/kubernetes/kubernetes/pull/109752

### CODE REVIEW

**Comment by lobziik** [comment]
Cherrypicked https://github.com/openshift/cluster-machine-approver/pull/167 and updated envtest

**Comment by JoelSpeed** [comment]
Sigh
```
E1019 10:05:31.497759       1 instances.go:400] Error creating EC2 instance: InsufficientInstanceCapacity: There is no Spot capacity available that matches your request.
	status code: 500, request id: d042f50d-dff1-4498-a6f9-6eca485b900c
E1019 10:05:31.497802       1 reconciler.go:93] ci-op-jzc8smhj-efb8d-mfnj4kbr2n-7d4wh: error creating machine: error creating EC2 instance: InsufficientInstanceCapacity: There is no Spot capacity available that matches your request.
```

/retest-required

**Comment by JoelSpeed** [comment]
/override ci/prow/e2e-aws-operator

This got 99% of the way through and failed on the penultimate test, which is known to be broken and we are working on this. I'm happy that this change hasn't broken anything

**Pull request merged**
