### PR TITLE
[OCPCLOUD-977] Bump scripts to Go 1.15

### PR DESCRIPTION
**Pull request by Danil-Grigorev**
Unblocks https://github.com/openshift/release/pull/13785

### CODE REVIEW

**Comment by JoelSpeed** [comment]
How come the gnostic files are being removed in this PR, bit odd 🤔

**Comment by Danil-Grigorev** [comment]
> How come the gnostic files are being removed in this PR, bit odd thinking

Can't separate go.mod changes here and revendor... So that's what I get vendoring with golang 1.15

**Comment by JoelSpeed** [comment]
The code still builds so it can't really be an issue, just odd it appeared here/now

/approve

**Review by alexander-demichev — APPROVED** [review]
/lgtm

**Pull request merged**
