### PR TITLE
OCPCLOUD-2044: Update to Kubernetes 1.27 deps

### PR DESCRIPTION
**Pull request by nrb**

### CODE REVIEW

**Comment by JoelSpeed** [comment]
/lgtm
/approve

CC @elmiko the balancer similar nodes tests seem to be failing again 😞

**Comment by nrb** [comment]
Pushed a new update for controller-runtime v0.15.0

**Comment by JoelSpeed** [comment]
/retest-required

Failures appear to be unrelated

**Comment by JoelSpeed** [comment]
Balance similar nodes test failed again, wondering if there's some issue on Azure now, CC @elmiko PR history on this one might be good to delve into

/retest-required

**Comment by JoelSpeed** [comment]
/retest

Fix for https://issues.redhat.com/browse/OCPBUGS-14338 has now merged so this should go green

**Pull request merged**
