### PR TITLE
Bug 1994480: Update dependencies to K8s 1.22 

### PR DESCRIPTION
**Pull request by JoelSpeed**
We should make sure our dependencies are up to date before the 4.9 code freeze

### CODE REVIEW

**Comment by elmiko** [comment]
although the cluster tests are all failing for various connectivity reasons (i suspect some flakes), the unit test failure is confusing to me. i tried to replicate locally, but am not getting the same error.

this seems to be common in the failures though,
```
make[1]: Entering directory `/go/src/github.com/openshift/cluster-machine-approver'
go test -v ./...
panic: mkdir /.cache: permission denied 
```

**Comment by JoelSpeed** [comment]
> although the cluster tests are all failing for various connectivity reasons (i suspect some flakes), the unit test failure is confusing to me. i tried to replicate locally, but am not getting the same error.
> 
> this seems to be common in the failures though,
> 
> ```
> make[1]: Entering directory `/go/src/github.com/openshift/cluster-machine-approver'
> go test -v ./...
> panic: mkdir /.cache: permission denied 
> ```

This should now be fixed by https://github.com/openshift/cluster-machine-approver/pull/128/commits/dc23c869d5d37e9e515eae76d746fdf77e1d5d85

**Comment by JoelSpeed** [comment]
/override ci/prow/e2e-gcp-operator

The test itself passed, there's something broken about the teardown and gathering console logs

```
INFO[2021-08-18T09:16:21Z] Running step e2e-gcp-operator-test.          
INFO[2021-08-18T10:22:11Z] Step e2e-gcp-operator-test succeeded after 1h5m50s.
```
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-machine-approver/128/pull-ci-openshift-cluster-machine-approver-master-e2e-gcp-operator/1427913063352242176

**Review by Fedosin — APPROVED** [review]
/lgtm

**Review by alexander-demichev — APPROVED** [review]
/approve

**Pull request merged**
