### PR TITLE
Fix registry path in Dockerfile

### PR DESCRIPTION
**Pull request by alexander-demichev**
Fix registry path in Dockerfile, `registry.svc.ci` is deprecated.

### CODE REVIEW

**Review by elmiko — CHANGES_REQUESTED** [review]
i think this should update the Dockerfile.rhel as well, it is using the same registry url

**Comment by Danil-Grigorev** [comment]
/approve

Seems passing prow/images

**Comment by alexander-demichev** [comment]
@elmiko Thanks! I added rhel dockerfile

**Review by elmiko — APPROVED** [review]
thanks Alex
/lgtm

**Comment by JoelSpeed** [comment]
This will conflict with #104 which is a superset of these changes. It would be preferable to get that PR merged instead

**Comment by alexander-demichev** [comment]
already fixed in other PR

**Pull request closed without merging**
