### PR TITLE
Revert "Operator restructure"

### PR DESCRIPTION
**Pull request by smarterclayton**
Reverts openshift/cluster-machine-approver#8

Post merge seeing a large number of e2e-aws failures across all repos on machine-approver-controller restarting.

### CODE REVIEW

**Comment by smarterclayton** [comment]
@wking if this greens I'm going to revert

**Comment by abhinavdahiya** [comment]
@smarterclayton this is green

**Comment by wking** [comment]
I dropped some log excerpts [here][1].

[1]: https://github.com/openshift/installer/pull/955#issuecomment-449532589

**Comment by enj** [comment]
Hmm restart technically occurrs because it lost leader election.  We could turn that off I guess.  The 127.0.0.1 ip also looks weird.

**Comment by smarterclayton** [comment]
Logs are in all the linked jobs

**Pull request merged**
