### PR TITLE
update to golang 1.17

### PR DESCRIPTION
**Pull request by elmiko**
This change updates the go.mod, makefile, dockerfiles, ci-operator.yaml, and the vendor directory to use golang 1.17 for building. it also adds a minor convenience option to the makefile that allows a user to override the build image.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
/lgtm cancel

The unit tests are broken here, this will need further investigation

**Comment by elmiko** [comment]
ack, thanks for the heads up. i'll investigate

**Comment by elmiko** [comment]
seeing a lot of these in the logs
```
Failed to retrieve current serving cert: x509: certificate has expired or is not yet valid: current time 2021-11-30T18:34:23Z is after 2021-11-18T20:12:00Z
```
wonder if we have some bad test data in here

**Comment by elmiko** [comment]
rebased on master with the unit test fix

**Pull request merged**
