### PR TITLE
Bug 1947785: Move certificates to v1

### PR DESCRIPTION
**Pull request by alexander-demichev**
Move certificates to v1 because v1beta1 will be removed in 4.9.

### CODE REVIEW

**Review by elmiko — APPROVED** [review]
/lgtm

**Comment by JoelSpeed** [comment]
/hold This isn't working correctly, if you look at the CSRs, they aren't being approved, even though the CSR approver is reconciling them. Something in this change breaks the approving/updating logic but there isn't logging to tell us what it might be.

This will need further investigation

**Pull request merged**
