### PR TITLE
Use controller runtime to initalise client with uncached objects

### PR DESCRIPTION
**Pull request by JoelSpeed**
This should be functionally equivalent looking at the code, this just simplifies the initialisation of the client by letting controller runtime set up the uncached objects rather than having to do this manually ourselves.

### CODE REVIEW

**Comment by Danil-Grigorev** [comment]
/lgtm
LGTM!

**Comment by lobziik** [comment]
Do we have test / CI signal for ensure that it works properly?

**Comment by JoelSpeed** [comment]
> Do we have test / CI signal for ensure that it works properly?

This is very hard to test, but in a way yes. If we regress here, then the disruptive tests for etcd quorum restore will start to fail again. The changes that originally motivated this change were affecting that specific test and the test started passing reliably once we fixed the issue with the caching

**Comment by lobziik** [comment]
>If we regress here, then the disruptive tests for etcd quorum restore will start to fail again. 

Sounds ok to me.

/test e2e-aws-disruptive

**Pull request closed without merging**
